name: Deploy via SSH + Git Pull

on:
  push:
    branches: [ main ]
    paths:
        - "public/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: SSH into remote host and pull latest changes
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 2222
          script: |
            cd /home/${{ secrets.SSH_USER }}/actions-1
            git fetch --all
            git reset --hard origin/main
            # optional: restart app/service
            #docker compose down
            #docker compose up -d --build
